version: "3.7"

services:
  mongodb:
    image : mongo
    container_name: the-good-resell-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${MANGO_DATA_PATH}/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  api:
    container_name: the-good-resell-api
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 3001:3000
  webpage:
    container_name: the-good-resell-webpage
    build:
      context: webpage/
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
